### ISSUE TITLE
Review user stories template doc

### ISSUE THREAD

**Issue by jordonezlucena** [camaraproject/WorkingGroups#6] opened 2022-01-18 11:48 UTC
Template link:
https://github.com/camaraproject/rep_main/blob/main/WorkingGroups/Commonalities/documentation/Deliverables/Userstory-template.md @

**Comment by Kevsy** [comment] 2022-02-24 10:55
Created [Pull Request 24](https://github.com/camaraproject/WorkingGroups/pull/24)

-    distinguished between 'Actors' and 'Roles'
-   added 'end user' as an actor and explained why
-   added 'privacy by design' in 'Linking user story to API design section

**Comment by jordonezlucena** [comment] 2022-03-08 11:23
@Kevsy: thanks for your good suggestions. Please see my comments inline below
 
-  **distinguished between 'Actors' and 'Roles'** -> I see your point. However, with the new separation, does it make sense to mark 'Actors' field as optional and 'role' filed as mandatory. From CAMARA viewpoint, I don't think we should restrict API usage to a particular actor. For example, the QoD API can be invoked by an hyperscaler or a large-scale content service provider or both. What's important for us is to define the customer role (user, administrator, business manager) that will consume the API. WDYT?
-   **added 'end user' as an actor and explained why** -> ok. 
-   **added 'privacy by design' in 'Linking user story to API design section** -> agree, and very good point.

**Comment by Kevsy** [comment] 2022-03-09 14:20
Thanks @jordonezlucena  - yes I agree with your good points. I have changed the text in [PR 24](https://github.com/camaraproject/WorkingGroups/pull/24) to better focus on Roles.

**Comment by T-sm** [comment] 2022-04-11 09:56
Thank you for your reviews, since there are no further comments this issue will be closed as agreed during our last _Commonalities Workgroup_ meeting.

**Closed** 2022-04-11 19:24 UTC
Labels: commonalities
