### ISSUE TITLE
Release v1.0.0

### ISSUE THREAD

**Issue by FabrizioMoggio** [camaraproject/WorkingGroups#139] opened 2023-01-30 08:19 UTC
As discussed for the GSMA OpenVerse deadline for the MWC, v1.0.0 should be released only after the CAMARA guidelines and documents are stable enough to guarantee that all the V1.0.0 releases for the different APIs are aligned with CAMARA specifications.

With this topic I just would like to **keep track of when the CAMARA documents are considered stable enough for an API to be checked against those documents and released as V1.0.0**.

Obviously it is mandatory  that the API must be completed, stable, and agreed by the partners, to be release as v1.0.0.

**Comment by shilpa-padgaonkar** [comment] 2023-02-01 14:30
Here are my 2-cents on this topic:
About commonalities guideline documentations
1.	There are several documents in commonalities which are living documents. This means, that they will need to evolve and mature over time. For e.g. there are currently some open issues/PRs (error model, headers, versioning) for updating the API guidelines doc or the subprojects are preparing a list of developer friendly terms/parameters to add to commonalities glossary document etc. 
2. The basic deliverables, which the commonalities set out to deliver (as agreed in an initial scope) when the working group started, have already been contributed in some shape or form (except the testing guidelines doc) and have different level of maturity depending on the complexity of the topics and will be refined over time.
3. Guideline documents in commonalities are best practices that subprojects are expected to follow when designing their APIs.  As there will always be scope for improvement for any written best practices, it should not stop any subproject to tag their APIs as stable if they think the APIs are mature enough to do so. 
About Stable APIs 
4. However, it is important to understand that calling an API stable comes with a very high level of commitment (guarantee) from the API provider/project side about its reliability and stability. A simple check if an API follows all guidelines in commonalities definitely should NOT be a sole driver for the decision. IMHO, as an API provider, after designing and implementing my (alpha)API and having friendly customers/users test it, I would like to check if the API is used enough, should I continue to offer it, does it need a re-design, incorporate all the testing feedback into improving my API and ensure that it has been very well tested at this stage (beta). Only after I can guarantee the reliability and stability of the API, would I want to mark it as stable. 
5. One can see in several successful open source projects (for e.g. Kubernetes Ref: https://kubernetes.io/docs/reference/using-api/#api-versioning), that it takes quite a while before they release a stable version of an API, as the expected maturity & reliability level of such stable APIs is quite high.
6. The above comments are not intended to deter anyone from releasing their APIs as stable, but to just bring an awareness that stable APIs are interpreted by consumers as a Guarantee.

**Comment by shilpa-padgaonkar** [comment] 2023-02-08 15:15
Independent support group that could help with compliance on request from subprojects & steering committee (TSC or otherwise). - Lyle

**Comment by FabrizioMoggio** [comment] 2023-02-09 10:44
@shilpa-padgaonkar 

A support group could be very useful. Are you also suggesting that v1.0.0 could be released after a "compliance verification" by this "compliance group". If I got it right, it seems to me a very good idea even if a bit time consuming for the "compliance group"  if done for every API. Anyway, if we could agree on that, it would be very helpful.

**Comment by shilpa-padgaonkar** [comment] 2023-02-10 05:18
@FabrizioMoggio : Yes, the general feedback from the group was that such an independent body would be useful. 

_Are you also suggesting that v1.0.0 could be released after a "compliance verification" by this "compliance group"._   No.

The comment from Lyle above, points more towards a support structure which sub-projects/steering committee can request guidance from rather than a top down approach. 

@lbertz02  Hope  I did not misunderstand.

**Comment by jordonezlucena** [comment] 2023-02-20 11:48
@shilpa-padgaonkar: is this support group transversal across all CAMARA Sub-Projects? Which partners will be integrating them? What is the pipeline for this group to work, i.e. input/outputs and associated timelines? Why no start drafting a doc to capture this? I think it'd be really helpful

**Comment by jordonezlucena** [comment] 2023-02-23 08:09
@FabrizioMoggio: in addition to the questions I made above regarding Shilpa's proposal on creating an independent support group, here's Telefónica take on which criteria an API shall comply to evolve towards v1.0.0:

- The API SHALL be aligned with the recommendations on AuthN/Z reported [here](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/CAMARA-AuthN-AuthZ-Concept.md)
- The API SHALL be aligned with the design guidelines documented [here](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/API-design-guidelines.md)

As you may have noted, user consent management is not included in this list. The reason is that this topic is no longer part of the commonalities discussion (it was decided to resume this activity into a newly approved Sub-Project). Additionally, it seems this topic may take few weeks to be agreed upon, so it does not sound reasonable to use it to condition the evolution towards v1.0.0. 

WDYT?

**Comment by jordonezlucena** [comment] 2023-03-07 16:03
Hi Fabrizio, CAMARA is in the process on changing WoW and decision making, with an updated governance expected in this month ahead.
From Telefónica standpoint, the criteria that should sustain going for V1.0.0 are the ones I posted in my previous comment. However, since this is a decision that may impact the whole CAMARA WoW, I think it is better to seek for guidance and recommendation from Chairman. He might have an immediate feedback on the wy forward, or he might suggest waiting for the re-shaped CAMARA governance. 
I include @MarkusKuemmerle in the loop for him to provide us with recommendations

**Comment by FabrizioMoggio** [comment] 2023-03-08 09:35
@hdamker very great comments. My purpose to mark the current version of the TI API as v1.0.0 is to have it tracked as stable and fully aligned with the CAMARA guidelines **before starting the implementation of the next version**. V1.0.0 indeed covers the LBO use case while v2.0.0 also covers User Mobility among Edges. 

Anyway my request is mainly focused to promote a clear definition of the process that leads to v1.0.0 in terms of compliancy to the documents or, as you correctly pointed out also, maybe, to step 6 of the Readiness Checklist (even if I hope it is not required).  @jordonezlucena what do you think about?

**Comment by jordonezlucena** [comment] 2023-03-12 12:57
I suggest waiting for the new governance and WoW (that are being reshaped now). We need to start working on release cycles, in order to manage expectations of API consumers and producers.

**Comment by jordonezlucena** [comment] 2023-04-12 18:52
@FabrizioMoggio: Since the new governance and WoW is taking time, I think we can start moving towards v1.0.0. TEF standpoint is that an API can be promoted to v1.0.0 (stable version) as long as:

- The API is compliant with the design guidelines documented [here](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/API-design-guidelines.md)
- The Authorisation and Authentication of the API is aligned with the recommendations documented [here](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/CAMARA-AuthN-AuthZ-Concept.md), in sections 4 and 5.
- The API does not compete with other API in the same sub-project -> this definitely needs to be solved through clear guidance for WoW.

@hdamker: please see Telefónica (TEF) responses to the points you noted in your earlier comment. 
- **Regarding 1)**, TEF have already implemented most of the APIs in version v0.x. The issue is that we are offering them in our Early Adopters Program, which is great. But in CAMARA, the scope of some APIs the scope keeps changing and increasing, actually with breaking changes. We think this is a bad message for developer community -- for example, let's assume that we define v0.2 and then v0.3 with non-backwards compatible changes. We prefer this approach instead: once version is released and stable, to freeze a formal release (this means v1.0) and keep discussions and evolution thinking of v1.1 or even v2.0 (depending on whether we just add functionality or we break compatibility). Some of the APIs are quite stable in both definition and in scope, like [HomeDevicesQoD](https://github.com/camaraproject/HomeDevicesQoD). Others are also quite stable but new features are being discussed -- some of them may take months to get stabilised. 
- Regarding 2), TEF don't agree. We think the approach you mention would work if the goal is only to validate the API with developers. However, in CAMARA the approach is slightly different: we keep on reviewing and adding new requirements (e.g., to accommodate new use cases) changing the v0.x no matter if breaking changes exist or not. We can't explain that unstability to developers.
- **Regarding 3)**, yes; indeed, that's TEF position. We want to offer a stable version.
- **Regarding 4)**, no matter that today we offer v0.x and one month later we offer v0.y with breaking change or v1.0 -- the issue will be the same. Early adopters know that this is the first release. We should not fear  having a version and some months later a new one -- instead, we should guarantee some stability with regards to scope in a release. 

 
. 

 

Regarding 4. No matter we offer 0.x and one month later 0.x+1 with breaking change or 1.0, the issue will be the same. Early adopters know that this is the first release. We should not fear of having a version and some months after a new one, but we should guarantee some stability with regards to scope in a release.

**Comment by FabrizioMoggio** [comment] 2023-04-26 15:28
**Conclusion**:

an API can be promoted to v1.0.0 (stable version) as long as:

The API is compliant with the design guidelines documented [here](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/API-design-guidelines.md)
The Authorisation and Authentication of the API is aligned with the recommendations documented [here](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/CAMARA-AuthN-AuthZ-Concept.md), in sections 4 and 5.
The API does not compete with other API in the same sub-project -> this definitely needs to be solved through clear guidance for WoW.

**Comment by FabrizioMoggio** [comment] 2023-05-17 13:06
Do we need to also consider the API Readiness Checklist?

https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/API-Readiness-Checklist.md

Step 5 is not clear yet.
Step 6 is not easy or fast to be accomplished.

**Comment by shilpa-padgaonkar** [comment] 2023-06-01 13:19
Yes, API readiness checklist should be considered. Though I must point out that its goal was to simply check if an API in Camara fulfills the minimum readiness criteria. So, it is not forcing any subproject to release v1 of the API simply because it meets the readiness criteria.

IMHO point 6 is a good test to check the readiness and acceptance of a Camara API. If this criteria needs to be changed from mandatory to optional, I would rather recommend you to get a consensus on it.

**Closed** 2023-06-29 13:40 UTC
Labels: commonalities
